### ISSUE TITLE
Push nbt-0.6 to Hackage

### ISSUE THREAD

**Issue by oldmanmike** [acfoltzer/nbt#10]
I'm running into build issues with Stackage lts-5.0 because nbt-5.1 still uses cereal (>=0.3.4 && <0.5). This is no longer the case in nbt-0.6 due to glguy's version bump of the upper bound for compatible cereal versions, so Hackage needs to be updated.

**Comment by acfoltzer** [comment]
Thanks for the reminder; not releasing it sooner was an oversight :+1:
